apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: dati-semantic-wordpress
  namespace: ndc-dev
  labels:
    application: dati-semantic-wordpress
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: dati-semantic-wordpress
  template:
    metadata:
      name: dati-semantic-wordpress
      creationTimestamp: null
      labels:
        application: dati-semantic-wordpress
        deploymentConfig: dati-semantic-wordpress
    spec:
      containers:
        - resources:
            limits:
              cpu: 800m
              memory: 2048Mi
            requests:
              cpu: 250m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: dati-semantic-wordpress
          ports:
            - name: wordpress
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          env:
            - name: XDG_CONFIG_HOME
              value: /tmp/
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: WPVAR_WP_HOME
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: WP_HOME
            - name: WPVAR_WP_SITEURL
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: WP_SITEURL
            - name: WPVAR_TABLE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: TABLE_PREFIX
            - name: WPVAR_WP_CONTENT_DIR
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: WP_CONTENT_DIR
            - name: WPVAR_FS_METHOD
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: FS_METHOD
            - name: WPVAR_WP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: WP_DEBUG
            - name: WPVAR_WP_DEBUG_LOG
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: WP_DEBUG_LOG
            - name: WPVAR_WP_DEBUG_DISPLAY
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: WP_DEBUG_DISPLAY
            - name: WPVAR_WP_POST_REVISIONS
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: WP_POST_REVISIONS
            - name: WPVAR_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: DB_HOST
            - name: WPVAR_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: DB_NAME
            - name: WPVAR_DB_CHARSET
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: DB_CHARSET
            - name: WPVAR_DB_COLLATE
              valueFrom:
                configMapKeyRef:
                  name: dev-example-config
                  key: DB_COLLATE
            - name: WPVAR_DB_USER
              valueFrom:
                secretKeyRef:
                  name: dev-example-db-secret
                  key: DB_USER
            - name: WPVAR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-example-db-secret
                  key: DB_PASSWORD
            - name: WPVAR_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: dev-example-wp-secret
                  key: AUTH_KEY
            - name: WPVAR_SECURE_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: dev-example-wp-secret
                  key: SECURE_AUTH_KEY
            - name: WPVAR_LOGGED_IN_KEY
              valueFrom:
                secretKeyRef:
                  name: dev-example-wp-secret
                  key: LOGGED_IN_KEY
            - name: WPVAR_NONCE_KEY
              valueFrom:
                secretKeyRef:
                  name: dev-example-wp-secret
                  key: NONCE_KEY
            - name: WPVAR_AUTH_SALT
              valueFrom:
                secretKeyRef:
                  name: dev-example-wp-secret
                  key: AUTH_SALT
            - name: WPVAR_SECURE_AUTH_SALT
              valueFrom:
                secretKeyRef:
                  name: dev-example-wp-secret
                  key: SECURE_AUTH_SALT
            - name: WPVAR_LOGGED_IN_SALT
              valueFrom:
                secretKeyRef:
                  name: dev-example-wp-secret
                  key: LOGGED_IN_SALT
            - name: WPVAR_NONCE_SALT
              valueFrom:
                secretKeyRef:
                  name: dev-example-wp-secret
                  key: NONCE_SALT
            - name: VOLUME_MOUNT_PATH
              value: "/var/www/example.com"
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
